INSERT INTO PESSOA(NOME_COMPLETO) VALUES ('Marcela de Albuquerque');



INSERT INTO ENDERECO(LOGRADOURO, CEP, NUMERO, CIDADE, UF, SITUACAO, PESSOA_ID)
VALUES ('RUA DAS FLORES', '89809-909', 123, 'LONDRINA', 'PR', 'PRIMARIA', 1);

INSERT INTO ENDERECO(LOGRADOURO, CEP, NUMERO, CIDADE, UF, SITUACAO, PESSOA_ID)
VALUES ('RUA DAS ORQUIDEAS', '89809-909', 1, 'LONDRINA', 'PR', 'PRIMARIA', 1);

INSERT INTO ENDERECO(LOGRADOURO, CEP, NUMERO, CIDADE, UF, SITUACAO, PESSOA_ID)
VALUES ('RUA DAS ROSAS', '89809-909', 3, 'LONDRINA', 'PR', 'PRIMARIA', 1);
